/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2_proyecto6_fredysalvador;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Fredy Salvador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
 private void abrir_ingresar(){
    jd_Ingresar.pack();
    jd_Ingresar.setLocationRelativeTo(this);
    jd_Ingresar.setModal(true);
    jd_Ingresar.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Ingresar = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jd_AgregarArtista = new javax.swing.JDialog();
        btAgregarArtista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnomartista = new javax.swing.JTextField();
        tcontrasenaartista = new javax.swing.JTextField();
        tnomartistico = new javax.swing.JTextField();
        tedadartista = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jd_AgregarCliente = new javax.swing.JDialog();
        tnomcliente = new javax.swing.JTextField();
        tcontrasenacliente = new javax.swing.JTextField();
        tedadcliente = new javax.swing.JTextField();
        btAgregarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jd_Arbol_Cliente = new javax.swing.JDialog();
        jd_Arbol_Artista = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ttitulop = new javax.swing.JTextField();
        AgregarArbolArtista = new javax.swing.JButton();
        tlanzamiento = new javax.swing.JComboBox();
        AgregarCancionArtista = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Artistas = new javax.swing.JList();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_Artistas = new javax.swing.JTree();
        jLabel23 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jd_Login = new javax.swing.JDialog();
        tcont = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btIngresar = new javax.swing.JButton();
        tusuar = new javax.swing.JTextField();
        jd_listaaruser = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsers = new javax.swing.JTable();
        bteliminarusuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        verusuario = new javax.swing.JButton();
        agregarusuarioscliente = new javax.swing.JButton();
        agregarusuariosartistas = new javax.swing.JButton();
        salirusuario = new javax.swing.JButton();
        arbolcliente = new javax.swing.JButton();
        arbolartista = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton5.setText("Registrar Artista");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Login Usuario");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu de Inicio");

        jButton7.setText("Registrar Cliente");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_IngresarLayout = new javax.swing.GroupLayout(jd_Ingresar.getContentPane());
        jd_Ingresar.getContentPane().setLayout(jd_IngresarLayout);
        jd_IngresarLayout.setHorizontalGroup(
            jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_IngresarLayout.setVerticalGroup(
            jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IngresarLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jd_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        btAgregarArtista.setText("Agregar");
        btAgregarArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarArtistaMouseClicked(evt);
            }
        });
        btAgregarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarArtistaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de Usuario:");

        jLabel3.setText("Contraseña de Usuario:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Nombre Artistico:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Agregar Artista");

        javax.swing.GroupLayout jd_AgregarArtistaLayout = new javax.swing.GroupLayout(jd_AgregarArtista.getContentPane());
        jd_AgregarArtista.getContentPane().setLayout(jd_AgregarArtistaLayout);
        jd_AgregarArtistaLayout.setHorizontalGroup(
            jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarArtistaLayout.createSequentialGroup()
                .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarArtistaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_AgregarArtistaLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tnomartista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_AgregarArtistaLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tedadartista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarArtistaLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tnomartistico, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarArtistaLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(tcontrasenaartista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_AgregarArtistaLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_AgregarArtistaLayout.setVerticalGroup(
            jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarArtistaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnomartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tcontrasenaartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tedadartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tnomartistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        btAgregarCliente.setText("Agregar");
        btAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarClienteMouseClicked(evt);
            }
        });

        jLabel7.setText("Nombre de Usuario:");

        jLabel8.setText("Contraseña de Usuario:");

        jLabel9.setText("Edad:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Agregar Clientes");

        javax.swing.GroupLayout jd_AgregarClienteLayout = new javax.swing.GroupLayout(jd_AgregarCliente.getContentPane());
        jd_AgregarCliente.getContentPane().setLayout(jd_AgregarClienteLayout);
        jd_AgregarClienteLayout.setHorizontalGroup(
            jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarClienteLayout.createSequentialGroup()
                .addGroup(jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarClienteLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_AgregarClienteLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_AgregarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tnomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_AgregarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tedadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tcontrasenacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_AgregarClienteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jd_AgregarClienteLayout.setVerticalGroup(
            jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarClienteLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tnomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tcontrasenacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tedadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jd_Arbol_ClienteLayout = new javax.swing.GroupLayout(jd_Arbol_Cliente.getContentPane());
        jd_Arbol_Cliente.getContentPane().setLayout(jd_Arbol_ClienteLayout);
        jd_Arbol_ClienteLayout.setHorizontalGroup(
            jd_Arbol_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        jd_Arbol_ClienteLayout.setVerticalGroup(
            jd_Arbol_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jLabel20.setText("Tipo de Lanzamiento:");

        jLabel21.setText("Titulo de Publicacion:");

        AgregarArbolArtista.setText("Agregar al arbol");
        AgregarArbolArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarArbolArtistaMouseClicked(evt);
            }
        });
        AgregarArbolArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarArbolArtistaActionPerformed(evt);
            }
        });

        tlanzamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Singles", "Albumes" }));

        AgregarCancionArtista.setText("Agregar Lista");
        AgregarCancionArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCancionArtistaMouseClicked(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jl_Artistas.setModel(new DefaultListModel());
        jl_Artistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ArtistasMouseClicked(evt);
            }
        });
        jl_Artistas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_ArtistasKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jl_Artistas);

        jLabel22.setText("Canciones");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Tipo Lanzamiento");
        jt_Artistas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Artistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ArtistasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_Artistas);

        jLabel23.setText("Tipo Lanzamiento");

        jButton10.setText("----->");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("Nombre Cancion:");

        jLabel25.setText("Tiempo de Duracion Min: ");

        jLabel26.setText("Referente Album:");

        javax.swing.GroupLayout jd_Arbol_ArtistaLayout = new javax.swing.GroupLayout(jd_Arbol_Artista.getContentPane());
        jd_Arbol_Artista.getContentPane().setLayout(jd_Arbol_ArtistaLayout);
        jd_Arbol_ArtistaLayout.setHorizontalGroup(
            jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                        .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(27, 27, 27)
                                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Arbol_ArtistaLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ttitulop, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Arbol_ArtistaLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tlanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                        .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                                .addComponent(AgregarCancionArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(AgregarArbolArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_Arbol_ArtistaLayout.setVerticalGroup(
            jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Arbol_ArtistaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ttitulop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(1, 1, 1)
                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jd_Arbol_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AgregarCancionArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarArbolArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jLabel6.setText("jLabel6");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("Ingresar al Sistema");

        jLabel13.setText("Usuario:");

        jLabel14.setText("Contraseña:");

        btIngresar.setText("Ingresar");
        btIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIngresarMouseClicked(evt);
            }
        });
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        btIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btIngresarKeyPressed(evt);
            }
        });

        tusuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tusuarMouseClicked(evt);
            }
        });
        tusuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginLayout = new javax.swing.GroupLayout(jd_Login.getContentPane());
        jd_Login.getContentPane().setLayout(jd_LoginLayout);
        jd_LoginLayout.setHorizontalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12))
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_LoginLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(11, 11, 11)))
                        .addGap(38, 38, 38)
                        .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tcont, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(tusuar)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jd_LoginLayout.setVerticalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(31, 31, 31)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tusuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsers);

        bteliminarusuario.setText("Eliminar");
        bteliminarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bteliminarusuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listaaruserLayout = new javax.swing.GroupLayout(jd_listaaruser.getContentPane());
        jd_listaaruser.getContentPane().setLayout(jd_listaaruserLayout);
        jd_listaaruserLayout.setHorizontalGroup(
            jd_listaaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaaruserLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(jd_listaaruserLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bteliminarusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_listaaruserLayout.setVerticalGroup(
            jd_listaaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaaruserLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bteliminarusuario)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jToolBar1.setRollover(true);

        jButton1.setText("Ingresar al Sistema");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        verusuario.setText("Ver Usuario + Eliminar");
        verusuario.setEnabled(false);
        verusuario.setFocusable(false);
        verusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verusuarioMouseClicked(evt);
            }
        });
        jToolBar1.add(verusuario);

        agregarusuarioscliente.setText("Agregar Cliente");
        agregarusuarioscliente.setEnabled(false);
        agregarusuarioscliente.setFocusable(false);
        agregarusuarioscliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarusuarioscliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(agregarusuarioscliente);

        agregarusuariosartistas.setText("Agregar Artista");
        agregarusuariosartistas.setEnabled(false);
        agregarusuariosartistas.setFocusable(false);
        agregarusuariosartistas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarusuariosartistas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(agregarusuariosartistas);

        salirusuario.setText("Salir del Sistema");
        salirusuario.setEnabled(false);
        salirusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(salirusuario);

        arbolcliente.setText("Arbol Cliente");
        arbolcliente.setEnabled(false);
        arbolcliente.setFocusable(false);
        arbolcliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arbolcliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        arbolcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolclienteMouseClicked(evt);
            }
        });
        jToolBar1.add(arbolcliente);

        arbolartista.setText("Arbol Artista");
        arbolartista.setEnabled(false);
        arbolartista.setFocusable(false);
        arbolartista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arbolartista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        arbolartista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolartistaMouseClicked(evt);
            }
        });
        jToolBar1.add(arbolartista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 271, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
abrir_ingresar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
                jd_AgregarArtista.pack();
    jd_AgregarArtista.setLocationRelativeTo(this);
    jd_AgregarArtista.setModal(true);
     jd_AgregarArtista.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          jd_AgregarCliente.pack();
    jd_AgregarCliente.setLocationRelativeTo(this);
    jd_AgregarCliente.setModal(true);
    jd_AgregarCliente.setVisible(true);
         
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         
    
    }//GEN-LAST:event_jButton5MouseClicked

    private void btAgregarArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarArtistaMouseClicked
        // TODO add your handling code here:
           String nombre, contrasena, nom_art;
           int edad;
        try {     
            nombre = tnomartista.getText();
            contrasena = tcontrasenaartista.getText();
            nom_art = tnomartistico.getText();
            edad = Integer.parseInt(tedadartista.getText());
 
            Artista p = new Artista(nombre, contrasena, edad, nom_art);
            
            usuarios.add(p);
            
            JOptionPane.showMessageDialog(this,
                 "Valores Ingresado Correctamente");
            tnomartista.setText("");
            tcontrasenaartista.setText("");
            tedadartista.setText("");
            tnomartistico.setText("");
            
                                jd_AgregarArtista.setVisible(false);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                 "Ocurrio un error y no se guardaron los datos");
        }

    }//GEN-LAST:event_btAgregarArtistaMouseClicked

    private void btAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarClienteMouseClicked
        // TODO add your handling code here:
                  String nombre, contrasena, nom_art;
           int edad;
        try {     
            nombre = tnomcliente.getText();
            contrasena = tcontrasenacliente.getText();
            edad = Integer.parseInt(tedadcliente.getText());
 
            Cliente p = new Cliente(nombre, contrasena, edad);
            
            usuarios.add(p);
            
            JOptionPane.showMessageDialog(this,
                 "Valores Ingresado Correctamente");
            tnomcliente.setText("");
            tcontrasenacliente.setText("");
            tedadcliente.setText("");
            
             jd_AgregarCliente.setVisible(false);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                 "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_btAgregarClienteMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    jd_Login.pack();
    jd_Login.setLocationRelativeTo(this);
    jd_Login.setModal(true);
    jd_Login.setVisible(true);
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void btIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIngresarMouseClicked
        // TODO add your handling code here:
        boolean bandera=false;
        for(Usuario temp : usuarios){
            if (temp.getUsername().equals(tusuar.getText())
                && temp.getPassword().equals(tcont.getText())
            ){

                bandera= true;
                break;
            }
        }

        if (bandera){
            tusuar.setText("");
            tcont.setText("");
            jButton1.setEnabled(false);
            verusuario.setEnabled(true);
            salirusuario.setEnabled(true);
            arbolcliente.setEnabled(true);
            arbolartista.setEnabled(true);
            

            jd_Login.setVisible(false);
            jd_Ingresar.setVisible(false);

        }else{
            JOptionPane.showMessageDialog(jd_Ingresar, "Usuario Equivocado");
        }

    }//GEN-LAST:event_btIngresarMouseClicked

    private void btIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btIngresarKeyPressed

        if (tcont.getText().length()>=0){

            btIngresar.setEnabled(true);

        }else{

            btIngresar.setEnabled(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btIngresarKeyPressed

    private void tusuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tusuarMouseClicked
        if(evt.getButton()==3){
           // jPopupMenu2.show(jd_Ingresar, evt.getX(), evt.getY());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tusuarMouseClicked

    private void tusuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusuarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_tusuarActionPerformed

    private void btAgregarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarArtistaActionPerformed

    private void AgregarArbolArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarArbolArtistaMouseClicked
        // TODO add your handling code here:
   DefaultTreeModel m = (DefaultTreeModel) jt_Artistas.getModel();
        DefaultMutableTreeNode raiz  = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_tipo;
        DefaultMutableTreeNode nodo_persona;
        nodo_tipo = new DefaultMutableTreeNode(tlanzamiento.getSelectedItem());
        nodo_persona = new DefaultMutableTreeNode(new Lanzamiento(ttitulop.getText(), (String) tlanzamiento.getSelectedItem()
                )
                );
        
        DefaultMutableTreeNode anio;
        DefaultMutableTreeNode edad;
        
   //     nodo_persona.add(anio);
       raiz.add(nodo_tipo);
        nodo_tipo.add(nodo_persona);
        m.reload();

    }//GEN-LAST:event_AgregarArbolArtistaMouseClicked

    private void AgregarCancionArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCancionArtistaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCancionArtistaMouseClicked

    private void jl_ArtistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ArtistasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_ArtistasMouseClicked

    private void jl_ArtistasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_ArtistasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_ArtistasKeyPressed

    private void jt_ArtistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ArtistasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_ArtistasMouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseClicked

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIngresarActionPerformed

    private void arbolclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolclienteMouseClicked
        // TODO add your handling code here:
     jd_Arbol_Cliente.pack();
     jd_Arbol_Cliente.setLocationRelativeTo(this);
     jd_Arbol_Cliente.setModal(true);
     jd_Arbol_Cliente.setVisible(true);
    }//GEN-LAST:event_arbolclienteMouseClicked

    private void arbolartistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolartistaMouseClicked
        // TODO add your handling code here:
        jd_Arbol_Artista.pack();
     jd_Arbol_Artista.setLocationRelativeTo(this);
     jd_Arbol_Artista.setModal(true);
     jd_Arbol_Artista.setVisible(true);
    }//GEN-LAST:event_arbolartistaMouseClicked

    private void AgregarArbolArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarArbolArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarArbolArtistaActionPerformed

    private void verusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verusuarioMouseClicked
        // TODO add your handling code here:
        jd_listaaruser.pack();
    jd_listaaruser.setLocationRelativeTo(this);
    jd_listaaruser.setModal(true);
    jd_listaaruser.setVisible(true);
        
        
          try {

            //limpiar tabla
            TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre Usuario", "Contraseña"
                    }
            ));
            
                  

            // TODO add your handling code here:
            for (Usuario t : usuarios) {
                Object[] row = {t.getUsername(), t.getPassword()};
                DefaultTableModel modelo = (DefaultTableModel) TablaUsers.getModel();
                modelo.addRow(row);
             TablaUsers.setModel(modelo);
            }
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }

            
    }//GEN-LAST:event_verusuarioMouseClicked

    private void TablaUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaUsersMouseClicked

    private void bteliminarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bteliminarusuarioMouseClicked
        // TODO add your handling code here:
          if (TablaUsers.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) TablaUsers.getModel();
            modelo.removeRow(TablaUsers.getSelectedRow());
            TablaUsers.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
             int selectedRow = TablaUsers.getSelectedRow();
            
            selectedRow = selectedRow + 1;
            usuarios.remove(selectedRow);
            
        }
        
    }//GEN-LAST:event_bteliminarusuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    ArrayList<Usuario> usuarios = new ArrayList();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarArbolArtista;
    private javax.swing.JButton AgregarCancionArtista;
    private javax.swing.JTable TablaUsers;
    private javax.swing.JButton agregarusuariosartistas;
    private javax.swing.JButton agregarusuarioscliente;
    private javax.swing.JButton arbolartista;
    private javax.swing.JButton arbolcliente;
    private javax.swing.JButton btAgregarArtista;
    private javax.swing.JButton btAgregarCliente;
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton bteliminarusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_AgregarArtista;
    private javax.swing.JDialog jd_AgregarCliente;
    private javax.swing.JDialog jd_Arbol_Artista;
    private javax.swing.JDialog jd_Arbol_Cliente;
    private javax.swing.JDialog jd_Ingresar;
    private javax.swing.JDialog jd_Login;
    private javax.swing.JDialog jd_listaaruser;
    private javax.swing.JList jl_Artistas;
    private javax.swing.JTree jt_Artistas;
    private javax.swing.JButton salirusuario;
    private javax.swing.JTextField tcont;
    private javax.swing.JTextField tcontrasenaartista;
    private javax.swing.JTextField tcontrasenacliente;
    private javax.swing.JTextField tedadartista;
    private javax.swing.JTextField tedadcliente;
    private javax.swing.JComboBox tlanzamiento;
    private javax.swing.JTextField tnomartista;
    private javax.swing.JTextField tnomartistico;
    private javax.swing.JTextField tnomcliente;
    private javax.swing.JTextField ttitulop;
    private javax.swing.JTextField tusuar;
    private javax.swing.JButton verusuario;
    // End of variables declaration//GEN-END:variables
}
